In [1]:
import pandas as pd

In [2]:
pwd

'/'

In [152]:
df = pd.read_csv('/Users/akmalpopalzi/Documents/GitHub/modelling-airbnbs-property-listing-dataset-/airbnb-property-listings/tabular_data/listing.csv')

In [5]:
df.head()

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    object
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
 19  Unnamed: 19           1 non-null      float64
dtypes: float64(10), int64(1), object(9)
memory usage: 154.5+ KB

In [7]:
df.isna().sum()

ID                        0
Category                  0
Title                     0
Description              88
Amenities                 0
Location                  0
guests                   19
beds                     43
bathrooms               100
Price_Night               0
Cleanliness_rating       98
Accuracy_rating          98
Communication_rating     98
Location_rating          98
Check-in_rating          98
Value_rating             98
amenities_count           0
url                       0
bedrooms                 82
Unnamed: 19             987
dtype: int64

In [8]:
df.columns

Index(['ID', 'Category', 'Title', 'Description', 'Amenities', 'Location',
       'guests', 'beds', 'bathrooms', 'Price_Night', 'Cleanliness_rating',
       'Accuracy_rating', 'Communication_rating', 'Location_rating',
       'Check-in_rating', 'Value_rating', 'amenities_count', 'url', 'bedrooms',
       'Unnamed: 19'],
      dtype='object')

In [31]:
df.Cleanliness_rating.isna

<bound method Series.isna of 0      4.6
1      4.3
2      4.2
3      4.8
4      NaN
      ...
983    4.8
984    4.8
985    4.7
986    NaN
987    4.9
Name: Cleanliness_rating, Length: 988, dtype: float64>

In [41]:
df[['Cleanliness_rating','Accuracy_rating','Communication_rating','Location_rating','Check-in_rating','Value_rating']]

,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating
0,4.6,4.7,4.3,5.0,4.3,4.3
1,4.3,4.7,4.6,4.9,4.7,4.5
2,4.2,4.6,4.8,4.8,4.8,4.7
3,4.8,4.9,4.9,4.9,5.0,4.6
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
983,4.8,5.0,4.9,4.9,5.0,4.9
984,4.8,5.0,5.0,5.0,5.0,4.8
985,4.7,4.8,5.0,5.0,5.0,4.7
986,NaN,NaN,NaN,NaN,NaN,NaN
987,4.9,4.9,4.9,4.9,4.9,4.3

### Function 1 - remove missing ratings

In [52]:
def remove_rows_with_missing_ratings(df):
    ratings = df[['Cleanliness_rating','Accuracy_rating','Communication_rating','Location_rating','Check-in_rating','Value_rating']].dropna()
    return ratings

In [45]:
df.head()

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN

In [68]:
df.Description[8]

'[\'About this space\', \'The Domaine proposes to make you live a unique experience in a beautiful place where a perched hut is set up to guarantee absolute privacy to really feel "out of time" to recharge your batteries cut off from civilization.\\nA private outdoor uncovered Jacuzzi awaits you\', \'The space\', \'The space\\nLuxury and nature the hut perched 100% comfort : heating, toilet, shower.\\nAn outdoor Jacuzzi not covered for 3 people\\nA monkey bridge, easy to reach by stairs is open to all without age limit and will please children.\\nPerched 5 meters high, close to the pond which guarantees a unique charm.\\nwith a view of the pond.\\nBreakfast not included but you can bring yours (nespresso available in the cabin)\\nOffice available microwave, fridge and dishes on request\', \'Guest access\', \'Guest access\\nentire accommodation\\nbarbecue in the park on request\', \'Other things to note\', \'Other things to note\\nthe site lends itself to weddings if necessary the cottage will not be available\']'

In [53]:
def combine_description_strings(df):
    descriptions_remove_null = df.Description.dropna()
    pass

In [71]:
test = df.Description[3]

In [72]:
test

'[\'About this space\', \'The Tree top cabin is situated in our peaceful woodland in the heart of Snowdonia. It has a shower (hot water included)and w.c and washbasin (no hot water in the washbasin).\\nLighting is provided from a 12v solar panel system.\\nA log burner is provided with free wood.\\nThere is a double bed.\\nThe private wood fired hot tub is situated on a balcony overlooking the woodland area.\\nPet friendly.\\nOutside seating is provided.\', \'The space\', \'The space\\nThis unique glamping experience has everything you need for a restful and idyllic break from everyday life. Wake up to bird song and the sound of the stream. Enjoy your own exclusive hot tub whilst sipping a glass of bubbly. Our Cabin is fully insulated and has everything you need for that perfect "rustic" getaway without compromising on quality and convenience.\\n\\nALL bedding and towels are included in your stay. You may like to bring extra towels for hot tub usage.\\n\\nA small log burner inside to keep you nice and cosy.\\n\\nThere is limited telephone signal.\', \'\', \'\']'

In [73]:
test.startswith('[')

True

In [88]:
test2 = test.replace('About this space','')

In [90]:
test3 = test2.replace('[','')

In [91]:
test3

'\'\', \'The Tree top cabin is situated in our peaceful woodland in the heart of Snowdonia. It has a shower (hot water included)and w.c and washbasin (no hot water in the washbasin).\\nLighting is provided from a 12v solar panel system.\\nA log burner is provided with free wood.\\nThere is a double bed.\\nThe private wood fired hot tub is situated on a balcony overlooking the woodland area.\\nPet friendly.\\nOutside seating is provided.\', \'The space\', \'The space\\nThis unique glamping experience has everything you need for a restful and idyllic break from everyday life. Wake up to bird song and the sound of the stream. Enjoy your own exclusive hot tub whilst sipping a glass of bubbly. Our Cabin is fully insulated and has everything you need for that perfect "rustic" getaway without compromising on quality and convenience.\\n\\nALL bedding and towels are included in your stay. You may like to bring extra towels for hot tub usage.\\n\\nA small log burner inside to keep you nice and cosy.\\n\\nThere is limited telephone signal.\', \'\', \'\']'

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    object
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
 19  Unnamed: 19           1 non-null      float64
dtypes: float64(10), int64(1), object(9)
memory usage: 154.5+ KB

In [95]:
from ast import literal_eval
b = df["Description"][1] = literal_eval(df["Description"][1])

/var/folders/j7/wpvkrkss313_f_v160vb65h80000gn/T/ipykernel_1111/604152607.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b = df["Description"][1] = literal_eval(df["Description"][1])

In [98]:
b

['About this space',
 "Come and spend a romantic stay with a couple or family, on the Domaine de l 'Arbre in Cabane\n\nA very pretty forest of 5 hectares shelters 8 beautiful huts they all have the dream names, unique and unprecedented.\n\nThey are housed in centuries-old trees out of sight, in osmosis with nature.\n\nThe site is preserved, your peace is assured. Nature is everywhere\n\nA treehouse to indulge, relax and go where no one will be looking for you!",
 'The space',
 'The space\nCabin perched in trees 8 meters high.\nThis cabin is beautiful. Its access via a board walkway and its platform adjoining 3 individual beds seduce them to the highest degree. It has a capacity of 3 people.',
 'Guest access',
 'Guest access\nYou will have access to the entire cabin, forest and park.\nSanitary facilities (showers and toilets) are at the reception, a 3-minute walk.',
 'Other things to note',
 'Other things to note\nAre you ready for an unusual stay?']

In [103]:
a = AirbnbDataPrep()

In [108]:
a = df.reset_index(drop = True, inplace = True)

In [109]:
a

In [110]:
a

In [117]:
df.drop('Unnamed: 19', inplace = True)

KeyError: "['Unnamed: 19'] not found in axis"

In [121]:
df.colummns

AttributeError: 'DataFrame' object has no attribute 'colummns'

In [122]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [123]:
df.columns

Index(['ID', 'Category', 'Title', 'Description', 'Amenities', 'Location',
       'guests', 'beds', 'bathrooms', 'Price_Night', 'Cleanliness_rating',
       'Accuracy_rating', 'Communication_rating', 'Location_rating',
       'Check-in_rating', 'Value_rating', 'amenities_count', 'url', 'bedrooms',
       'Unnamed: 19'],
      dtype='object')

In [125]:
df.drop('Unnamed: 19', inplace = True, axis = 1)

In [126]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2

In [129]:
for i in range(len(df.Description)):
    pass

988

In [131]:
df.Description[0] = literal_eval(df.Description[0])

/var/folders/j7/wpvkrkss313_f_v160vb65h80000gn/T/ipykernel_1111/3739021685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Description[0] = literal_eval(df.Description[0])

In [132]:
df.Description[0]

['About this space',
 "Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon's Egg.",
 'The space',
 'The space\nThe true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.',
 '',
 '',
 '',
 'Other things to note\nYou are entering a remote woodland hideaway for a digital detox: there is very patchy mobile signal and limited internet connectivity.']

In [145]:
for i in range(0,999):
    df.Description[i] = literal_eval(df.Description[i])

/var/folders/j7/wpvkrkss313_f_v160vb65h80000gn/T/ipykernel_1111/4113915140.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Description[i] = literal_eval(df.Description[i])

ValueError: malformed node or string: nan

In [139]:
df.Description[1]

'[\'About this space\', "Come and spend a romantic stay with a couple or family, on the Domaine de l \'Arbre in Cabane\\n\\nA very pretty forest of 5 hectares shelters 8 beautiful huts they all have the dream names, unique and unprecedented.\\n\\nThey are housed in centuries-old trees out of sight, in osmosis with nature.\\n\\nThe site is preserved, your peace is assured. Nature is everywhere\\n\\nA treehouse to indulge, relax and go where no one will be looking for you!", \'The space\', \'The space\\nCabin perched in trees 8 meters high.\\nThis cabin is beautiful. Its access via a board walkway and its platform adjoining 3 individual beds seduce them to the highest degree. It has a capacity of 3 people.\', \'Guest access\', \'Guest access\\nYou will have access to the entire cabin, forest and park.\\nSanitary facilities (showers and toilets) are at the reception, a 3-minute walk.\', \'Other things to note\', \'Other things to note\\nAre you ready for an unusual stay?\']'

In [151]:
df.Description[987]

"['About this space', 'Sea Scenes is a homely two bedroom groundfloor apartment located on Hayling‚Äôs beautiful stretch of beach and perfectly situated for stunning views across the Solent.\\n\\nHayling Island is ideal for holiday makers and families as it retains all the attractions of a traditional seaside resort. One of the biggest attractions is the Funland Amusement Park at Beachlands, which has everything from roller coasters to a games arcade and a soft play area. The Hayling Seaside Railway that runs from Beachlands to Eastoke Corner is equally popular.\\n\\nThe island is also well known for its watersports ‚Äì in fact windsurfing was invented here ‚Äì and miles of glorious seafront. The local water is perfect for sailing, windsurfing, power boating, jet skiing and more.\\n\\nThere are various great places to eat if you don‚Äôt feel like cooking, from nice restaurants to pubs and of course a wide range of takeaways. Hayling is also well served by shops, so anything you need during your stay is right on hand!\\n\\nHowever, if you feel like venturing out and exploring nearby areas, the attractions of Portsmouth, Southsea, Emsworth and Staunton Country Park are all close by.\\n\\nThe property itself is well furnished and feels comfortable and welcoming.\\n\\nThe living/kitchen area is open and spacious with amazing views overlooking the sea. The living area consists of comfortable sofas and a smart TV. The kitchen area is well equipped with a kettle, Nespresso maker, cafetiere, cooker, fridge, freezer, microwave, toaster, washing machine and dryer, along with a wooden dining table that seats four.\\n\\nThe master bedroom has a queen size bed, a stylish dressing table and a smart TV. The second bedroom has a single bed which can be pulled out to make a comfortable king size bed, please note: once the bed has been pulled out there is limited room in the bedroom.\\n\\nThere is a stylish walk in shower and a separate WC.\\n\\nThere is no BBQ provided for the garden, however, you are more than welcome to bring your own and enjoy the amazing scenery.\\n\\nWIFI is included with this property and there is enough parking for 2 cars.']"

In [153]:
df.Description.dropna(inplace = True)

In [155]:
df.Description

0      ['About this space', "Escape to one of these t...
1      ['About this space', "Come and spend a romanti...
2      ['About this space', 'Rustic cabin between the...
3      ['About this space', 'The Tree top cabin is si...
4      ['About this space', 'Feel refreshed at this u...
                             ...
983    ['About this space', 'Light roomy space with o...
984    ['About this space', 'This specious two bedroo...
985    ['About this space', 'With all the modern amen...
986    ['About this space', 'Sleeps 10. A large Beach...
987    ['About this space', 'Sea Scenes is a homely t...
Name: Description, Length: 988, dtype: object

In [156]:
df[['Cleanliness_rating','Accuracy_rating','Communication_rating','Location_rating','Check-in_rating','Value_rating']].dropna(inplace = True)

/var/folders/j7/wpvkrkss313_f_v160vb65h80000gn/T/ipykernel_1111/3853597702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Cleanliness_rating','Accuracy_rating','Communication_rating','Location_rating','Check-in_rating','Value_rating']].dropna(inplace = True)

In [157]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [158]:
df.isna().sum()

ID                        0
Category                  0
Title                     0
Description              88
Amenities                 0
Location                  0
guests                   19
beds                     43
bathrooms               100
Price_Night               0
Cleanliness_rating       98
Accuracy_rating          98
Communication_rating     98
Location_rating          98
Check-in_rating          98
Value_rating             98
amenities_count           0
url                       0
bedrooms                 82
Unnamed: 19             987
dtype: int64

In [159]:
df = pd.read_csv('/Users/akmalpopalzi/Documents/GitHub/modelling-airbnbs-property-listing-dataset-/airbnb-property-listings/tabular_data/listing.csv')

In [160]:
df.Description[0]

'[\'About this space\', "Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon\'s Egg.", \'The space\', \'The space\\nThe true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.\', \'\', \'\', \'\', \'Other things to note\\nYou are entering a remote woodland hideaway for a digital detox: there is very patchy mobile signal and limited internet connectivity.\']'

In [164]:
df.dropna(subset = ['Description', 'Value_rating'], inplace = True)

In [165]:
df.isna().sum()

ID                        0
Category                  0
Title                     0
Description               0
Amenities                 0
Location                  0
guests                   15
beds                     29
bathrooms                65
Price_Night               0
Cleanliness_rating        0
Accuracy_rating           0
Communication_rating      0
Location_rating           0
Check-in_rating           0
Value_rating              0
amenities_count           0
url                       0
bedrooms                 70
Unnamed: 19             829
dtype: int64

In [167]:
for i in range(len(df.Description)):
    df.Description[i] = literal_eval(df.Description[i])

/var/folders/j7/wpvkrkss313_f_v160vb65h80000gn/T/ipykernel_1111/65143504.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Description[i] = literal_eval(df.Description[i])

KeyError: 4

['About this space',
 "Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon's Egg.",
 'The space',
 'The space\nThe true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.',
 '',
 '',
 '',
 'Other things to note\nYou are entering a remote woodland hideaway for a digital detox: there is very patchy mobile signal and limited internet connectivity.']

In [169]:
df.Description[3]

['About this space',
 'The Tree top cabin is situated in our peaceful woodland in the heart of Snowdonia. It has a shower (hot water included)and w.c and washbasin (no hot water in the washbasin).\nLighting is provided from a 12v solar panel system.\nA log burner is provided with free wood.\nThere is a double bed.\nThe private wood fired hot tub is situated on a balcony overlooking the woodland area.\nPet friendly.\nOutside seating is provided.',
 'The space',
 'The space\nThis unique glamping experience has everything you need for a restful and idyllic break from everyday life. Wake up to bird song and the sound of the stream. Enjoy your own exclusive hot tub whilst sipping a glass of bubbly. Our Cabin is fully insulated and has everything you need for that perfect "rustic" getaway without compromising on quality and convenience.\n\nALL bedding and towels are included in your stay. You may like to bring extra towels for hot tub usage.\n\nA small log burner inside to keep you nice and cosy.\n\nThere is limited telephone signal.',
 '',
 '']

"['About this space', 'At a glance....\\n\\nCompletely refurbished in 2016/17, SeaScape is the ideal place to take advantage of the beautiful Sussex coastline.\\n\\nSituated just a stone‚Äôs throw away from the sea front promenade it boasts fully opening bi-fold doors on to a balcony with sea views stretching right to the tip of Eastbourne', 'The space', 'The space\\nCompletely refurbished is 2017, SeaScape offers a delightful living space, complete with balcony overlooking the sea.\\n\\nOffering a spacious double room plus a small double at the rear of the apartment, SeaScape is perfect for couples, looking for a quiet relaxing get away.', 'Guest access', 'Guest access\\nGuests have access to the full apartment including a front balcony and rear stairwell balcony']"

In [266]:
df = pd.read_csv('/Users/akmalpopalzi/Documents/GitHub/modelling-airbnbs-property-listing-dataset-/airbnb-property-listings/tabular_data/listing.csv')

In [267]:
df.iloc[586]

ID                                   4c917b3c-d693-4ee4-a321-f5babc728dc9
Category                                                    Amazing pools
Title                                       Stunning Cotswolds Water Park
Description                                            sleeps 6 with pool
Amenities               ['About this space', 'Enjoy a discount for boo...
Location                ['What this place offers', 'Bathroom', 'Hair d...
guests                            Somerford Keynes England United Kingdom
beds                                                                  6.0
bathrooms                                                             4.0
Price_Night                                                             3
Cleanliness_rating                                                  200.0
Accuracy_rating                                                       4.8
Communication_rating                                                  4.9
Location_rating                                                       5.0
Check-in_rating                                                       4.8
Value_rating                                                          4.9
amenities_count                                                       4.7
url                                                                    46
bedrooms                https://www.airbnb.co.uk/rooms/49009981?adults...
Unnamed: 19                                                           3.0
Name: 586, dtype: object

In [268]:
df.drop('Unnamed: 19', axis = 1, inplace = True)

In [269]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    object
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
dtypes: float64(9), int64(1), object(9)
memory usage: 146.8+ KB

In [271]:
df.Category = df.Category.astype('category')

In [272]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    category
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
dtypes: category(1), float64(9), int64(1), object(8)
memory usage: 140.2+ KB

In [273]:
df.drop(index = 586, inplace = True)

In [274]:
df.iloc[586]

ID                                   943e9242-7cfe-4db2-bb56-d7147fef352e
Category                                                    Amazing pools
Title                    The Burrow - Luxurious Pet Friendly, 3 Bed Lodge
Description             ['About this space', "Set in a peaceful area o...
Amenities               ['What this place offers', 'Bathroom', 'Shampo...
Location                                  Cotswold England United Kingdom
guests                                                                  6
beds                                                                  5.0
bathrooms                                                             1.5
Price_Night                                                           163
Cleanliness_rating                                                    5.0
Accuracy_rating                                                       4.9
Communication_rating                                                  4.9
Location_rating                                                       4.9
Check-in_rating                                                       4.9
Value_rating                                                          4.9
amenities_count                                                      37.0
url                     https://www.airbnb.co.uk/rooms/41170958?adults...
bedrooms                                                                3
Name: 587, dtype: object

In [275]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2

In [276]:
df[df.Category == 'Amazing Pools']

Empty DataFrame
Columns: [ID, Category, Title, Description, Amenities, Location, guests, beds, bathrooms, Price_Night, Cleanliness_rating, Accuracy_rating, Communication_rating, Location_rating, Check-in_rating, Value_rating, amenities_count, url, bedrooms]
Index: []

In [277]:
df.head()

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1

In [278]:
df.isna().sum()

ID                        0
Category                  0
Title                     0
Description              88
Amenities                 0
Location                  0
guests                   19
beds                     43
bathrooms               100
Price_Night               0
Cleanliness_rating       98
Accuracy_rating          98
Communication_rating     98
Location_rating          98
Check-in_rating          98
Value_rating             98
amenities_count           0
url                       0
bedrooms                 82
dtype: int64

In [279]:
df.dropna(subset = ['Description','Cleanliness_rating','Accuracy_rating',"Communication_rating","Location_rating","Check-in_rating","Value_rating"], inplace = True)

In [280]:
df.isna().sum()

ID                       0
Category                 0
Title                    0
Description              0
Amenities                0
Location                 0
guests                  15
beds                    29
bathrooms               65
Price_Night              0
Cleanliness_rating       0
Accuracy_rating          0
Communication_rating     0
Location_rating          0
Check-in_rating          0
Value_rating             0
amenities_count          0
url                      0
bedrooms                70
dtype: int64

In [281]:
df.reset_index(drop = True, inplace = True)

In [282]:
for i in range(len(df.Description)):
    df.Description[i] = literal_eval(df.Description[i])

/var/folders/j7/wpvkrkss313_f_v160vb65h80000gn/T/ipykernel_1111/65143504.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Description[i] = literal_eval(df.Description[i])

In [283]:
df.Description[0]

['About this space',
 "Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon's Egg.",
 'The space',
 'The space\nThe true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.',
 '',
 '',
 '',
 'Other things to note\nYou are entering a remote woodland hideaway for a digital detox: there is very patchy mobile signal and limited internet connectivity.']

In [287]:
phrases = ['About this space',
           'The space',
           '',
           "  ",
           " "
           'Other things to note',
           'Guest access']

In [288]:
for index, values in enumerate(df.Description[0]):
        print(index,values)
        if values in phrases:
                df.Description[0].pop(index)

0 Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon's Egg.
1 The space
The true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.
2

In [289]:
df.Description[0]

["Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon's Egg.",
 'The space\nThe true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.',
 'Other things to note\nYou are entering a remote woodland hideaway for a digital detox: there is very patchy mobile signal and limited internet connectivity.']

In [290]:
df.head()

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,[Escape to one of these two fabulous Tree Tent...,"['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"[About this space, Come and spend a romantic s...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"[About this space, Rustic cabin between the pi...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"[About this space, The Tree top cabin is situa...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN
4,cfe479b9-c8f8-44af-9bc6-46ede9f14bb5,Treehouses,Treehouse near Paris Disney,"[About this space, Charming cabin nestled in t...","['What this place offers', 'Bathroom', 'Hair d...",Le Plessis-Feu-Aussoux √éle-de-France France,4,3.0,1.0,143,5.0,4.9,5.0,4.7,5.0,4.7,32.0,https://www.airbnb.co.uk/rooms/935398?adults=1...,2

In [291]:
df.isna().sum()

ID                       0
Category                 0
Title                    0
Description              0
Amenities                0
Location                 0
guests                  15
beds                    29
bathrooms               65
Price_Night              0
Cleanliness_rating       0
Accuracy_rating          0
Communication_rating     0
Location_rating          0
Check-in_rating          0
Value_rating             0
amenities_count          0
url                      0
bedrooms                70
dtype: int64

In [295]:
b = df.copy()

In [301]:
b.head()

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,[Escape to one of these two fabulous Tree Tent...,"['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"[About this space, Come and spend a romantic s...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"[About this space, Rustic cabin between the pi...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"[About this space, The Tree top cabin is situa...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN
4,cfe479b9-c8f8-44af-9bc6-46ede9f14bb5,Treehouses,Treehouse near Paris Disney,"[About this space, Charming cabin nestled in t...","['What this place offers', 'Bathroom', 'Hair d...",Le Plessis-Feu-Aussoux √éle-de-France France,4,3.0,1.0,143,5.0,4.9,5.0,4.7,5.0,4.7,32.0,https://www.airbnb.co.uk/rooms/935398?adults=1...,2

In [308]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 829 entries, 0 to 828
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    829 non-null    object
 1   Category              829 non-null    category
 2   Title                 829 non-null    object
 3   Description           829 non-null    object
 4   Amenities             829 non-null    object
 5   Location              829 non-null    object
 6   guests                814 non-null    object
 7   beds                  800 non-null    float64
 8   bathrooms             764 non-null    float64
 9   Price_Night           829 non-null    int64
 10  Cleanliness_rating    829 non-null    float64
 11  Accuracy_rating       829 non-null    float64
 12  Communication_rating  829 non-null    float64
 13  Location_rating       829 non-null    float64
 14  Check-in_rating       829 non-null    float64
 15  Value_rating          829 non-null    float64
 16  amenities_count       829 non-null    float64
 17  url                   829 non-null    object
 18  bedrooms              759 non-null    object
dtypes: category(1), float64(9), int64(1), object(8)
memory usage: 117.7+ KB

In [311]:
columns = ['guests','beds', 'bathrooms', 'bedrooms']

In [312]:
for item in columns:
    print(df[item].isna().sum())

15
29
65
70

In [313]:
df['guests'] = df['guests'].where(df['guests'].isin(['no', 'n/a', 'N/A','NaN']), 1)

In [314]:
df.guests.isna().sum()

0

In [315]:
columns = ['guests','beds', 'bathrooms', 'bedrooms']
for item in columns:
     b[item] =b[item].where(df[item].isin(['no', 'n/a', 'N/A','NaN']), 1)

In [316]:
b.isna().sum()

ID                      0
Category                0
Title                   0
Description             0
Amenities               0
Location                0
guests                  0
beds                    0
bathrooms               0
Price_Night             0
Cleanliness_rating      0
Accuracy_rating         0
Communication_rating    0
Location_rating         0
Check-in_rating         0
Value_rating            0
amenities_count         0
url                     0
bedrooms                0
dtype: int64